insert into users values(101, 'Karachi, Pakistan', 'ali@example.com', 'Ali', 'Mehmood', 'admin', 'ssn101', 'alibaksh');
insert into users values(102, 'New York, USA', 'kreddy@example.com', 'Kalyan', 'Reddy', 'admin', 'ssn102', 'kreddy');
insert into users values(103, 'New Jersey, USA', 'gwiser@example.com', 'Greg', 'Wiser', 'admin', 'ssn103', 'gwiser');
insert into users values(104, 'California, USA', 'dmark@example.com', 'David', 'Mark', 'admin', 'ssn104', 'dmark'); 
insert into orders values( 2001, 'order11', 101);        
insert into orders values( 2002, 'order12', 101);
insert into orders values( 2003, 'order13', 101);
insert into orders values( 2004, 'order21', 102);
insert into orders values( 2005, 'order22', 102);
insert into orders values( 2006, 'order31', 103);
